from typing import Optional

from PyQt5 import QtCore, QtGui, QtWidgets


class Wheel_table(QtWidgets.QWidget):
    def __init__(
        self, width: float, height: float, parent=None, x: Optional[float] = 0, y: Optional[float] = 0
    ):
        super().__init__(parent=parent)
        self.width = width
        self.height = height
        self.parent = parent
        self.x = x or 5 * self.width / 16
        self.y = y or self.height / 15

    def display_currents(self, currents: list):
        self.r_front_current.setText(f"{round(currents[5], 1)}")
        self.r_mid_current.setText(f"{round(currents[4], 1)}")
        self.r_back_current.setText(f"{round(currents[1], 1)}")
        self.l_front_current.setText(f"{round(currents[2], 1)}")
        self.l_mid_current.setText(f"{round(currents[3], 1)}")
        self.l_back_current.setText(f"{round(currents[0], 1)}")

    def setup(self):
        self.table_frame = QtWidgets.QFrame(self.parent)
        self.table_frame.setGeometry(QtCore.QRect(self.x, self.y, 7 * self.width / 24, self.height / 2.16))
        self.table_frame.setStyleSheet("")
        self.table_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.table_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.table_frame.setObjectName("table_frame")
        self.wheel_motor_table_label = QtWidgets.QLabel(self.table_frame)
        self.wheel_motor_table_label.setGeometry(
            QtCore.QRect(self.width / 192, self.height / 108, self.width / 3.56, self.height / 45)
        )
        font = QtGui.QFont()
        font.setPointSize(self.width / 128)
        self.wheel_motor_table_label.setFont(font)
        self.wheel_motor_table_label.setAlignment(QtCore.Qt.AlignCenter)
        self.wheel_motor_table_label.setObjectName("wheel_motor_table_label")
        self.layoutWidget = QtWidgets.QWidget(self.table_frame)
        self.layoutWidget.setGeometry(
            QtCore.QRect(self.width / 192, self.height / 27, self.width / 3.56, self.height / 2.4)
        )
        self.layoutWidget.setObjectName("layoutWidget")
        self.wheel_motor_table = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.wheel_motor_table.setContentsMargins(0, 0, 0, 0)
        self.wheel_motor_table.setSpacing(0)
        self.wheel_motor_table.setObjectName("wheel_motor_table")
        self.table_head = QtWidgets.QHBoxLayout()
        self.table_head.setObjectName("table_head")
        self.table_head.setSpacing(0)
        self.motor_title = QtWidgets.QLabel(self.layoutWidget)
        self.motor_title.setAlignment(QtCore.Qt.AlignCenter)
        self.motor_title.setObjectName("motor_title")
        self.table_head.addWidget(self.motor_title)
        self.line_17 = QtWidgets.QFrame(self.layoutWidget)
        self.line_17.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_17.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.table_head.addWidget(self.line_17)
        self.status_title = QtWidgets.QLabel(self.layoutWidget)
        self.status_title.setAlignment(QtCore.Qt.AlignCenter)
        self.status_title.setObjectName("status_title")
        self.table_head.addWidget(self.status_title)
        self.line_23 = QtWidgets.QFrame(self.layoutWidget)
        self.line_23.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_23.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.table_head.addWidget(self.line_23)
        self.speed_title = QtWidgets.QLabel(self.layoutWidget)
        self.speed_title.setAlignment(QtCore.Qt.AlignCenter)
        self.speed_title.setObjectName("speed_title")
        self.table_head.addWidget(self.speed_title)
        self.line_22 = QtWidgets.QFrame(self.layoutWidget)
        self.line_22.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_22.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.table_head.addWidget(self.line_22)
        self.current_title = QtWidgets.QLabel(self.layoutWidget)
        self.current_title.setAlignment(QtCore.Qt.AlignCenter)
        self.current_title.setObjectName("current_title")
        self.table_head.addWidget(self.current_title)
        self.wheel_motor_table.addLayout(self.table_head)
        self.line_6 = QtWidgets.QFrame(self.layoutWidget)
        self.line_6.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.wheel_motor_table.addWidget(self.line_6)
        self.r_front_row = QtWidgets.QHBoxLayout()
        self.r_front_row.setObjectName("r_front_row")
        self.r_front_row.setSpacing(0)
        self.r_front_label = QtWidgets.QLabel(self.layoutWidget)
        self.r_front_label.setAlignment(QtCore.Qt.AlignCenter)
        self.r_front_label.setObjectName("r_front_label")
        self.r_front_row.addWidget(self.r_front_label)
        self.line_13 = QtWidgets.QFrame(self.layoutWidget)
        self.line_13.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.r_front_row.addWidget(self.line_13)
        self.r_front_status = QtWidgets.QLabel(self.layoutWidget)
        self.r_front_status.setAlignment(QtCore.Qt.AlignCenter)
        self.r_front_status.setObjectName("r_front_status")
        self.r_front_row.addWidget(self.r_front_status)
        self.line_14 = QtWidgets.QFrame(self.layoutWidget)
        self.line_14.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.r_front_row.addWidget(self.line_14)
        self.r_front_speed = QtWidgets.QLabel(self.layoutWidget)
        self.r_front_speed.setAlignment(QtCore.Qt.AlignCenter)
        self.r_front_speed.setObjectName("r_front_speed")
        self.r_front_row.addWidget(self.r_front_speed)
        self.line_15 = QtWidgets.QFrame(self.layoutWidget)
        self.line_15.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.r_front_row.addWidget(self.line_15)
        self.r_front_current = QtWidgets.QLabel(self.layoutWidget)
        self.r_front_current.setAlignment(QtCore.Qt.AlignCenter)
        self.r_front_current.setObjectName("r_front_current")
        self.r_front_row.addWidget(self.r_front_current)
        self.wheel_motor_table.addLayout(self.r_front_row)
        self.line = QtWidgets.QFrame(self.layoutWidget)
        self.line.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.wheel_motor_table.addWidget(self.line)
        self.r_mid_row = QtWidgets.QHBoxLayout()
        self.r_mid_row.setObjectName("r_mid_row")
        self.r_mid_row.setSpacing(0)
        self.r_mid_label = QtWidgets.QLabel(self.layoutWidget)
        self.r_mid_label.setAlignment(QtCore.Qt.AlignCenter)
        self.r_mid_label.setObjectName("r_mid_label")
        self.r_mid_row.addWidget(self.r_mid_label)
        self.line_30 = QtWidgets.QFrame(self.layoutWidget)
        self.line_30.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_30.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_30.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_30.setObjectName("line_30")
        self.r_mid_row.addWidget(self.line_30)
        self.r_mid_status = QtWidgets.QLabel(self.layoutWidget)
        self.r_mid_status.setAlignment(QtCore.Qt.AlignCenter)
        self.r_mid_status.setObjectName("r_mid_status")
        self.r_mid_row.addWidget(self.r_mid_status)
        self.line_27 = QtWidgets.QFrame(self.layoutWidget)
        self.line_27.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_27.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_27.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_27.setObjectName("line_27")
        self.r_mid_row.addWidget(self.line_27)
        self.r_mid_speed = QtWidgets.QLabel(self.layoutWidget)
        self.r_mid_speed.setAlignment(QtCore.Qt.AlignCenter)
        self.r_mid_speed.setObjectName("r_mid_speed")
        self.r_mid_row.addWidget(self.r_mid_speed)
        self.line_28 = QtWidgets.QFrame(self.layoutWidget)
        self.line_28.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_28.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_28.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_28.setObjectName("line_28")
        self.r_mid_row.addWidget(self.line_28)
        self.r_mid_current = QtWidgets.QLabel(self.layoutWidget)
        self.r_mid_current.setAlignment(QtCore.Qt.AlignCenter)
        self.r_mid_current.setObjectName("r_mid_current")
        self.r_mid_row.addWidget(self.r_mid_current)
        self.wheel_motor_table.addLayout(self.r_mid_row)
        self.line_2 = QtWidgets.QFrame(self.layoutWidget)
        self.line_2.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.wheel_motor_table.addWidget(self.line_2)
        self.r_back_row = QtWidgets.QHBoxLayout()
        self.r_back_row.setObjectName("r_back_row")
        self.r_back_row.setSpacing(0)
        self.r_back_label = QtWidgets.QLabel(self.layoutWidget)
        self.r_back_label.setAlignment(QtCore.Qt.AlignCenter)
        self.r_back_label.setObjectName("r_back_label")
        self.r_back_row.addWidget(self.r_back_label)
        self.line_24 = QtWidgets.QFrame(self.layoutWidget)
        self.line_24.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_24.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_24.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_24.setObjectName("line_24")
        self.r_back_row.addWidget(self.line_24)
        self.r_back_status = QtWidgets.QLabel(self.layoutWidget)
        self.r_back_status.setAlignment(QtCore.Qt.AlignCenter)
        self.r_back_status.setObjectName("r_back_status")
        self.r_back_row.addWidget(self.r_back_status)
        self.line_25 = QtWidgets.QFrame(self.layoutWidget)
        self.line_25.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_25.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_25.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_25.setObjectName("line_25")
        self.r_back_row.addWidget(self.line_25)
        self.r_back_speed = QtWidgets.QLabel(self.layoutWidget)
        self.r_back_speed.setAlignment(QtCore.Qt.AlignCenter)
        self.r_back_speed.setObjectName("r_back_speed")
        self.r_back_row.addWidget(self.r_back_speed)
        self.line_20 = QtWidgets.QFrame(self.layoutWidget)
        self.line_20.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_20.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.r_back_row.addWidget(self.line_20)
        self.r_back_current = QtWidgets.QLabel(self.layoutWidget)
        self.r_back_current.setAlignment(QtCore.Qt.AlignCenter)
        self.r_back_current.setObjectName("r_back_current")
        self.r_back_row.addWidget(self.r_back_current)
        self.wheel_motor_table.addLayout(self.r_back_row)
        self.line_3 = QtWidgets.QFrame(self.layoutWidget)
        self.line_3.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.wheel_motor_table.addWidget(self.line_3)
        self.l_front_row = QtWidgets.QHBoxLayout()
        self.l_front_row.setObjectName("l_front_row")
        self.l_front_row.setSpacing(0)
        self.l_front_label = QtWidgets.QLabel(self.layoutWidget)
        self.l_front_label.setAlignment(QtCore.Qt.AlignCenter)
        self.l_front_label.setObjectName("l_front_label")
        self.l_front_row.addWidget(self.l_front_label)
        self.line_11 = QtWidgets.QFrame(self.layoutWidget)
        self.line_11.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.l_front_row.addWidget(self.line_11)
        self.l_front_status = QtWidgets.QLabel(self.layoutWidget)
        self.l_front_status.setAlignment(QtCore.Qt.AlignCenter)
        self.l_front_status.setObjectName("l_front_status")
        self.l_front_row.addWidget(self.l_front_status)
        self.line_29 = QtWidgets.QFrame(self.layoutWidget)
        self.line_29.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_29.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_29.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_29.setObjectName("line_29")
        self.l_front_row.addWidget(self.line_29)
        self.l_front_speed = QtWidgets.QLabel(self.layoutWidget)
        self.l_front_speed.setAlignment(QtCore.Qt.AlignCenter)
        self.l_front_speed.setObjectName("l_front_speed")
        self.l_front_row.addWidget(self.l_front_speed)
        self.line_19 = QtWidgets.QFrame(self.layoutWidget)
        self.line_19.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_19.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.l_front_row.addWidget(self.line_19)
        self.l_front_current = QtWidgets.QLabel(self.layoutWidget)
        self.l_front_current.setAlignment(QtCore.Qt.AlignCenter)
        self.l_front_current.setObjectName("l_front_current")
        self.l_front_row.addWidget(self.l_front_current)
        self.wheel_motor_table.addLayout(self.l_front_row)
        self.line_4 = QtWidgets.QFrame(self.layoutWidget)
        self.line_4.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.wheel_motor_table.addWidget(self.line_4)
        self.l_mid_row = QtWidgets.QHBoxLayout()
        self.l_mid_row.setObjectName("l_mid_row")
        self.l_mid_row.setSpacing(0)
        self.l_mid_label = QtWidgets.QLabel(self.layoutWidget)
        self.l_mid_label.setAlignment(QtCore.Qt.AlignCenter)
        self.l_mid_label.setObjectName("l_mid_label")
        self.l_mid_row.addWidget(self.l_mid_label)
        self.line_32 = QtWidgets.QFrame(self.layoutWidget)
        self.line_32.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_32.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_32.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_32.setObjectName("line_32")
        self.l_mid_row.addWidget(self.line_32)
        self.l_mid_status = QtWidgets.QLabel(self.layoutWidget)
        self.l_mid_status.setAlignment(QtCore.Qt.AlignCenter)
        self.l_mid_status.setObjectName("l_mid_status")
        self.l_mid_row.addWidget(self.l_mid_status)
        self.line_26 = QtWidgets.QFrame(self.layoutWidget)
        self.line_26.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_26.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_26.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_26.setObjectName("line_26")
        self.l_mid_row.addWidget(self.line_26)
        self.l_mid_speed = QtWidgets.QLabel(self.layoutWidget)
        self.l_mid_speed.setAlignment(QtCore.Qt.AlignCenter)
        self.l_mid_speed.setObjectName("l_mid_speed")
        self.l_mid_row.addWidget(self.l_mid_speed)
        self.line_18 = QtWidgets.QFrame(self.layoutWidget)
        self.line_18.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_18.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.l_mid_row.addWidget(self.line_18)
        self.l_mid_current = QtWidgets.QLabel(self.layoutWidget)
        self.l_mid_current.setAlignment(QtCore.Qt.AlignCenter)
        self.l_mid_current.setObjectName("l_mid_current")
        self.l_mid_row.addWidget(self.l_mid_current)
        self.wheel_motor_table.addLayout(self.l_mid_row)
        self.line_5 = QtWidgets.QFrame(self.layoutWidget)
        self.line_5.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.wheel_motor_table.addWidget(self.line_5)
        self.l_back_row = QtWidgets.QHBoxLayout()
        self.l_back_row.setObjectName("l_back_row")
        self.l_back_row.setSpacing(0)
        self.l_back_label = QtWidgets.QLabel(self.layoutWidget)
        self.l_back_label.setAlignment(QtCore.Qt.AlignCenter)
        self.l_back_label.setObjectName("l_back_label")
        self.l_back_row.addWidget(self.l_back_label)
        self.line_31 = QtWidgets.QFrame(self.layoutWidget)
        self.line_31.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_31.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_31.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_31.setObjectName("line_31")
        self.l_back_row.addWidget(self.line_31)
        self.l_back_status = QtWidgets.QLabel(self.layoutWidget)
        self.l_back_status.setAlignment(QtCore.Qt.AlignCenter)
        self.l_back_status.setObjectName("l_back_status")
        self.l_back_row.addWidget(self.l_back_status)
        self.line_12 = QtWidgets.QFrame(self.layoutWidget)
        self.line_12.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.l_back_row.addWidget(self.line_12)
        self.l_back_speed = QtWidgets.QLabel(self.layoutWidget)
        self.l_back_speed.setAlignment(QtCore.Qt.AlignCenter)
        self.l_back_speed.setObjectName("l_back_speed")
        self.l_back_row.addWidget(self.l_back_speed)
        self.line_16 = QtWidgets.QFrame(self.layoutWidget)
        self.line_16.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_16.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.l_back_row.addWidget(self.line_16)
        self.l_back_current = QtWidgets.QLabel(self.layoutWidget)
        self.l_back_current.setAlignment(QtCore.Qt.AlignCenter)
        self.l_back_current.setObjectName("l_back_current")
        self.l_back_row.addWidget(self.l_back_current)
        self.wheel_motor_table.addLayout(self.l_back_row)

        _translate = QtCore.QCoreApplication.translate
        self.wheel_motor_table_label.setText(_translate("MainWindow", "Wheel Motor Table"))
        self.motor_title.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center">Motor</p><p align="center">(Number)</p></body></html>',
            )
        )
        self.status_title.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center">Status</p><p align="center">(Alive / Dead)</p></body></html>',
            )
        )
        self.speed_title.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center">Speed</p><p align="center">(RPM)</p></body></html>',
            )
        )
        self.current_title.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center">Current</p><p align="center">(A)</p></body></html>',
            )
        )
        self.r_front_label.setText("R Front")
        self.r_front_status.setText(_translate("MainWindow", "N/A"))
        self.r_front_speed.setText(_translate("MainWindow", "-"))
        self.r_front_current.setText(_translate("MainWindow", "N/A"))
        self.r_mid_label.setText(_translate("MainWindow", "R Mid"))
        self.r_mid_status.setText(_translate("MainWindow", "N/A"))
        self.r_mid_speed.setText(_translate("MainWindow", "-"))
        self.r_mid_current.setText(_translate("MainWindow", "N/A"))
        self.r_back_label.setText(_translate("MainWindow", "R Back"))
        self.r_back_status.setText(_translate("MainWindow", "N/A"))
        self.r_back_speed.setText(_translate("MainWindow", "-"))
        self.r_back_current.setText(_translate("MainWindow", "N/A"))
        self.l_front_label.setText(_translate("MainWindow", "L Front"))
        self.l_front_status.setText(_translate("MainWindow", "N/A"))
        self.l_front_speed.setText(_translate("MainWindow", "-"))
        self.l_front_current.setText(_translate("MainWindow", "N/A"))
        self.l_mid_label.setText(_translate("MainWindow", "L Mid"))
        self.l_mid_status.setText(_translate("MainWindow", "N/A"))
        self.l_mid_speed.setText(_translate("MainWindow", "-"))
        self.l_mid_current.setText(_translate("MainWindow", "N/A"))
        self.l_back_label.setText(_translate("MainWindow", "L Back"))
        self.l_back_status.setText(_translate("MainWindow", "N/A"))
        self.l_back_speed.setText(_translate("MainWindow", "-"))
        self.l_back_current.setText(_translate("MainWindow", "N/A"))


class Arm_table(QtWidgets.QWidget):
    def __init__(
        self, width: float, height: float, parent=None, x: Optional[float] = 0, y: Optional[float] = 0
    ):
        super().__init__(parent=parent)
        self.width = width
        self.height = height
        self.parent = parent
        self.x = x or 5 * self.width / 16
        self.y = y or self.height / 15

    def display_currents(self, currents: list):
        self.m1_current.setText(f"{round(currents[3], 1)}")
        self.m2_current.setText(f"{round(currents[2], 1)}")
        self.m3_current.setText(f"{round(currents[1], 1)}")
        self.m4_current.setText(f"{round(currents[0], 1)}")
        self.m5_current.setText(f"{round(currents[4], 1)}")
        self.m6_current.setText(f"{round(currents[5], 1)}")

    def setup(self):
        self.table_frame_3 = QtWidgets.QFrame(self.parent)
        self.table_frame_3.setGeometry(QtCore.QRect(self.x, self.y, self.width / 3.4, self.height / 2.16))
        self.table_frame_3.setStyleSheet("")
        self.table_frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.table_frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.table_frame_3.setObjectName("table_frame_3")
        self.arm_motor_table_title = QtWidgets.QLabel(self.table_frame_3)
        self.arm_motor_table_title.setGeometry(
            QtCore.QRect(self.width / 192, self.height / 108, 0.28 * self.width, self.height / 54)
        )
        font = QtGui.QFont()
        font.setPointSize(self.width / 128)
        self.arm_motor_table_title.setFont(font)
        self.arm_motor_table_title.setAlignment(QtCore.Qt.AlignCenter)
        self.arm_motor_table_title.setObjectName("arm_motor_table_title")
        self.layoutWidget_4 = QtWidgets.QWidget(self.table_frame_3)
        self.layoutWidget_4.setGeometry(
            QtCore.QRect(self.width / 192, self.height / 27, self.width / 3.56, self.height / 2.4)
        )
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.arm_motor_table = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.arm_motor_table.setContentsMargins(0, 0, 0, 0)
        self.arm_motor_table.setSpacing(0)
        self.arm_motor_table.setObjectName("arm_motor_table")
        self.table_head_4 = QtWidgets.QHBoxLayout()
        self.table_head_4.setSpacing(0)
        self.table_head_4.setObjectName("table_head_4")
        self.motor_title_3 = QtWidgets.QLabel(self.layoutWidget_4)
        self.motor_title_3.setAlignment(QtCore.Qt.AlignCenter)
        self.motor_title_3.setObjectName("motor_title_3")
        self.table_head_4.addWidget(self.motor_title_3)
        self.line_82 = QtWidgets.QFrame(self.layoutWidget_4)
        self.line_82.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_82.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_82.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_82.setObjectName("line_82")
        self.table_head_4.addWidget(self.line_82)
        self.status_title_3 = QtWidgets.QLabel(self.layoutWidget_4)
        self.status_title_3.setAlignment(QtCore.Qt.AlignCenter)
        self.status_title_3.setObjectName("status_title_3")
        self.table_head_4.addWidget(self.status_title_3)
        self.line_83 = QtWidgets.QFrame(self.layoutWidget_4)
        self.line_83.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_83.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_83.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_83.setObjectName("line_83")
        self.table_head_4.addWidget(self.line_83)
        self.position_title = QtWidgets.QLabel(self.layoutWidget_4)
        self.position_title.setAlignment(QtCore.Qt.AlignCenter)
        self.position_title.setObjectName("position_title")
        self.table_head_4.addWidget(self.position_title)
        self.line_84 = QtWidgets.QFrame(self.layoutWidget_4)
        self.line_84.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_84.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_84.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_84.setObjectName("line_84")
        self.table_head_4.addWidget(self.line_84)
        self.current_title_3 = QtWidgets.QLabel(self.layoutWidget_4)
        self.current_title_3.setAlignment(QtCore.Qt.AlignCenter)
        self.current_title_3.setObjectName("current_title_3")
        self.table_head_4.addWidget(self.current_title_3)
        self.arm_motor_table.addLayout(self.table_head_4)
        self.line_85 = QtWidgets.QFrame(self.layoutWidget_4)
        self.line_85.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_85.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_85.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_85.setObjectName("line_85")
        self.arm_motor_table.addWidget(self.line_85)
        self.m1_row = QtWidgets.QHBoxLayout()
        self.m1_row.setSpacing(0)
        self.m1_row.setObjectName("m1_row")
        self.m1_label = QtWidgets.QLabel(self.layoutWidget_4)
        self.m1_label.setAlignment(QtCore.Qt.AlignCenter)
        self.m1_label.setObjectName("m1_label")
        self.m1_row.addWidget(self.m1_label)
        self.line_86 = QtWidgets.QFrame(self.layoutWidget_4)
        self.line_86.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_86.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_86.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_86.setObjectName("line_86")
        self.m1_row.addWidget(self.line_86)
        self.m1_status = QtWidgets.QLabel(self.layoutWidget_4)
        self.m1_status.setAlignment(QtCore.Qt.AlignCenter)
        self.m1_status.setObjectName("m1_status")
        self.m1_row.addWidget(self.m1_status)
        self.line_87 = QtWidgets.QFrame(self.layoutWidget_4)
        self.line_87.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_87.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_87.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_87.setObjectName("line_87")
        self.m1_row.addWidget(self.line_87)
        self.m1_position = QtWidgets.QLabel(self.layoutWidget_4)
        self.m1_position.setAlignment(QtCore.Qt.AlignCenter)
        self.m1_position.setObjectName("m1_position")
        self.m1_row.addWidget(self.m1_position)
        self.line_88 = QtWidgets.QFrame(self.layoutWidget_4)
        self.line_88.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_88.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_88.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_88.setObjectName("line_88")
        self.m1_row.addWidget(self.line_88)
        self.m1_current = QtWidgets.QLabel(self.layoutWidget_4)
        self.m1_current.setAlignment(QtCore.Qt.AlignCenter)
        self.m1_current.setObjectName("m1_current")
        self.m1_row.addWidget(self.m1_current)
        self.arm_motor_table.addLayout(self.m1_row)
        self.line_89 = QtWidgets.QFrame(self.layoutWidget_4)
        self.line_89.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_89.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_89.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_89.setObjectName("line_89")
        self.arm_motor_table.addWidget(self.line_89)
        self.m2_row = QtWidgets.QHBoxLayout()
        self.m2_row.setSpacing(0)
        self.m2_row.setObjectName("m2_row")
        self.m2_label = QtWidgets.QLabel(self.layoutWidget_4)
        self.m2_label.setAlignment(QtCore.Qt.AlignCenter)
        self.m2_label.setObjectName("m2_label")
        self.m2_row.addWidget(self.m2_label)
        self.line_90 = QtWidgets.QFrame(self.layoutWidget_4)
        self.line_90.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_90.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_90.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_90.setObjectName("line_90")
        self.m2_row.addWidget(self.line_90)
        self.m2_status = QtWidgets.QLabel(self.layoutWidget_4)
        self.m2_status.setAlignment(QtCore.Qt.AlignCenter)
        self.m2_status.setObjectName("m2_status")
        self.m2_row.addWidget(self.m2_status)
        self.line_91 = QtWidgets.QFrame(self.layoutWidget_4)
        self.line_91.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_91.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_91.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_91.setObjectName("line_91")
        self.m2_row.addWidget(self.line_91)
        self.m2_position = QtWidgets.QLabel(self.layoutWidget_4)
        self.m2_position.setAlignment(QtCore.Qt.AlignCenter)
        self.m2_position.setObjectName("m2_position")
        self.m2_row.addWidget(self.m2_position)
        self.line_92 = QtWidgets.QFrame(self.layoutWidget_4)
        self.line_92.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_92.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_92.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_92.setObjectName("line_92")
        self.m2_row.addWidget(self.line_92)
        self.m2_current = QtWidgets.QLabel(self.layoutWidget_4)
        self.m2_current.setAlignment(QtCore.Qt.AlignCenter)
        self.m2_current.setObjectName("m2_current")
        self.m2_row.addWidget(self.m2_current)
        self.arm_motor_table.addLayout(self.m2_row)
        self.line_93 = QtWidgets.QFrame(self.layoutWidget_4)
        self.line_93.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_93.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_93.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_93.setObjectName("line_93")
        self.arm_motor_table.addWidget(self.line_93)
        self.m3_row = QtWidgets.QHBoxLayout()
        self.m3_row.setSpacing(0)
        self.m3_row.setObjectName("m3_row")
        self.m3_label = QtWidgets.QLabel(self.layoutWidget_4)
        self.m3_label.setAlignment(QtCore.Qt.AlignCenter)
        self.m3_label.setObjectName("m3_label")
        self.m3_row.addWidget(self.m3_label)
        self.line_94 = QtWidgets.QFrame(self.layoutWidget_4)
        self.line_94.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_94.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_94.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_94.setObjectName("line_94")
        self.m3_row.addWidget(self.line_94)
        self.m3_status = QtWidgets.QLabel(self.layoutWidget_4)
        self.m3_status.setAlignment(QtCore.Qt.AlignCenter)
        self.m3_status.setObjectName("m3_status")
        self.m3_row.addWidget(self.m3_status)
        self.line_95 = QtWidgets.QFrame(self.layoutWidget_4)
        self.line_95.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_95.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_95.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_95.setObjectName("line_95")
        self.m3_row.addWidget(self.line_95)
        self.m3_position = QtWidgets.QLabel(self.layoutWidget_4)
        self.m3_position.setAlignment(QtCore.Qt.AlignCenter)
        self.m3_position.setObjectName("m3_position")
        self.m3_row.addWidget(self.m3_position)
        self.line_96 = QtWidgets.QFrame(self.layoutWidget_4)
        self.line_96.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_96.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_96.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_96.setObjectName("line_96")
        self.m3_row.addWidget(self.line_96)
        self.m3_current = QtWidgets.QLabel(self.layoutWidget_4)
        self.m3_current.setAlignment(QtCore.Qt.AlignCenter)
        self.m3_current.setObjectName("m3_current")
        self.m3_row.addWidget(self.m3_current)
        self.arm_motor_table.addLayout(self.m3_row)
        self.line_55 = QtWidgets.QFrame(self.layoutWidget_4)
        self.line_55.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_55.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_55.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_55.setObjectName("line_55")
        self.arm_motor_table.addWidget(self.line_55)
        self.m4_row = QtWidgets.QHBoxLayout()
        self.m4_row.setSpacing(0)
        self.m4_row.setObjectName("m4_row")
        self.m4_label = QtWidgets.QLabel(self.layoutWidget_4)
        self.m4_label.setAlignment(QtCore.Qt.AlignCenter)
        self.m4_label.setObjectName("m4_label")
        self.m4_row.addWidget(self.m4_label)
        self.line_98 = QtWidgets.QFrame(self.layoutWidget_4)
        self.line_98.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_98.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_98.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_98.setObjectName("line_98")
        self.m4_row.addWidget(self.line_98)
        self.m4_status = QtWidgets.QLabel(self.layoutWidget_4)
        self.m4_status.setAlignment(QtCore.Qt.AlignCenter)
        self.m4_status.setObjectName("m4_status")
        self.m4_row.addWidget(self.m4_status)
        self.line_99 = QtWidgets.QFrame(self.layoutWidget_4)
        self.line_99.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_99.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_99.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_99.setObjectName("line_99")
        self.m4_row.addWidget(self.line_99)
        self.m4_position = QtWidgets.QLabel(self.layoutWidget_4)
        self.m4_position.setAlignment(QtCore.Qt.AlignCenter)
        self.m4_position.setObjectName("m4_position")
        self.m4_row.addWidget(self.m4_position)
        self.line_56 = QtWidgets.QFrame(self.layoutWidget_4)
        self.line_56.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_56.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_56.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_56.setObjectName("line_56")
        self.m4_row.addWidget(self.line_56)
        self.m4_current = QtWidgets.QLabel(self.layoutWidget_4)
        self.m4_current.setAlignment(QtCore.Qt.AlignCenter)
        self.m4_current.setObjectName("m4_current")
        self.m4_row.addWidget(self.m4_current)
        self.arm_motor_table.addLayout(self.m4_row)
        self.line_101 = QtWidgets.QFrame(self.layoutWidget_4)
        self.line_101.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_101.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_101.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_101.setObjectName("line_101")
        self.arm_motor_table.addWidget(self.line_101)
        self.m5_row = QtWidgets.QHBoxLayout()
        self.m5_row.setSpacing(0)
        self.m5_row.setObjectName("m5_row")
        self.m5_label = QtWidgets.QLabel(self.layoutWidget_4)
        self.m5_label.setAlignment(QtCore.Qt.AlignCenter)
        self.m5_label.setObjectName("m5_label")
        self.m5_row.addWidget(self.m5_label)
        self.line_102 = QtWidgets.QFrame(self.layoutWidget_4)
        self.line_102.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_102.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_102.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_102.setObjectName("line_102")
        self.m5_row.addWidget(self.line_102)
        self.m5_status = QtWidgets.QLabel(self.layoutWidget_4)
        self.m5_status.setAlignment(QtCore.Qt.AlignCenter)
        self.m5_status.setObjectName("m5_status")
        self.m5_row.addWidget(self.m5_status)
        self.line_103 = QtWidgets.QFrame(self.layoutWidget_4)
        self.line_103.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_103.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_103.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_103.setObjectName("line_103")
        self.m5_row.addWidget(self.line_103)
        self.m5_position = QtWidgets.QLabel(self.layoutWidget_4)
        self.m5_position.setAlignment(QtCore.Qt.AlignCenter)
        self.m5_position.setObjectName("m5_position")
        self.m5_row.addWidget(self.m5_position)
        self.line_104 = QtWidgets.QFrame(self.layoutWidget_4)
        self.line_104.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_104.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_104.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_104.setObjectName("line_104")
        self.m5_row.addWidget(self.line_104)
        self.m5_current = QtWidgets.QLabel(self.layoutWidget_4)
        self.m5_current.setAlignment(QtCore.Qt.AlignCenter)
        self.m5_current.setObjectName("m5_current")
        self.m5_row.addWidget(self.m5_current)
        self.arm_motor_table.addLayout(self.m5_row)
        self.line_105 = QtWidgets.QFrame(self.layoutWidget_4)
        self.line_105.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_105.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_105.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_105.setObjectName("line_105")
        self.arm_motor_table.addWidget(self.line_105)
        self.m6_row = QtWidgets.QHBoxLayout()
        self.m6_row.setSpacing(0)
        self.m6_row.setObjectName("m6_row")
        self.m6_label = QtWidgets.QLabel(self.layoutWidget_4)
        self.m6_label.setAlignment(QtCore.Qt.AlignCenter)
        self.m6_label.setObjectName("m6_label")
        self.m6_row.addWidget(self.m6_label)
        self.line_106 = QtWidgets.QFrame(self.layoutWidget_4)
        self.line_106.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_106.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_106.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_106.setObjectName("line_106")
        self.m6_row.addWidget(self.line_106)
        self.m6_status = QtWidgets.QLabel(self.layoutWidget_4)
        self.m6_status.setAlignment(QtCore.Qt.AlignCenter)
        self.m6_status.setObjectName("m6_status")
        self.m6_row.addWidget(self.m6_status)
        self.line_107 = QtWidgets.QFrame(self.layoutWidget_4)
        self.line_107.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_107.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_107.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_107.setObjectName("line_107")
        self.m6_row.addWidget(self.line_107)
        self.m6_position = QtWidgets.QLabel(self.layoutWidget_4)
        self.m6_position.setAlignment(QtCore.Qt.AlignCenter)
        self.m6_position.setObjectName("m6_position")
        self.m6_row.addWidget(self.m6_position)
        self.line_108 = QtWidgets.QFrame(self.layoutWidget_4)
        self.line_108.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_108.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_108.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_108.setObjectName("line_108")
        self.m6_row.addWidget(self.line_108)
        self.m6_current = QtWidgets.QLabel(self.layoutWidget_4)
        self.m6_current.setAlignment(QtCore.Qt.AlignCenter)
        self.m6_current.setObjectName("m6_current")
        self.m6_row.addWidget(self.m6_current)
        self.arm_motor_table.addLayout(self.m6_row)

        _translate = QtCore.QCoreApplication.translate
        self.arm_motor_table_title.setText(_translate("MainWindow", "Arm Motor Table"))
        self.motor_title_3.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center">Motor</p><p align="center">(Number)</p></body></html>',
            )
        )
        self.status_title_3.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center">Status</p><p align="center">(Alive / Dead)</p></body></html>',
            )
        )
        self.position_title.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center">Position</p><p align="center">(Degrees)</p></body></html>',
            )
        )
        self.current_title_3.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center">Current</p><p align="center">(A)</p></body></html>',
            )
        )
        self.m1_label.setText(_translate("MainWindow", "M1\n" "(Shoulder Swivel)"))
        self.m1_status.setText(_translate("MainWindow", "N/A"))
        self.m1_position.setText(_translate("MainWindow", "-"))
        self.m1_current.setText(_translate("MainWindow", "N/A"))
        self.m2_label.setText(_translate("MainWindow", "M2\n" "(Shoulder Flex)"))
        self.m2_status.setText(_translate("MainWindow", "N/A"))
        self.m2_position.setText(_translate("MainWindow", "-"))
        self.m2_current.setText(_translate("MainWindow", "N/A"))
        self.m3_label.setText(_translate("MainWindow", "M3\n" "(Elbow Flex)"))
        self.m3_status.setText(_translate("MainWindow", "N/A"))
        self.m3_position.setText(_translate("MainWindow", "-"))
        self.m3_current.setText(_translate("MainWindow", "N/A"))
        self.m4_label.setText(_translate("MainWindow", "M4\n" "(Wrist Flex)"))
        self.m4_status.setText(_translate("MainWindow", "N/A"))
        self.m4_position.setText(_translate("MainWindow", "-"))
        self.m4_current.setText(_translate("MainWindow", "N/A"))
        self.m5_label.setText(_translate("MainWindow", "M5\n" "(Wrist Twist)"))
        self.m5_status.setText(_translate("MainWindow", "N/A"))
        self.m5_position.setText(_translate("MainWindow", "-"))
        self.m5_current.setText(_translate("MainWindow", "N/A"))
        self.m6_label.setText(_translate("MainWindow", "M6\n" "(Gripper)"))
        self.m6_status.setText(_translate("MainWindow", "N/A"))
        self.m6_position.setText(_translate("MainWindow", "-"))
        self.m6_current.setText(_translate("MainWindow", "N/A"))


class Pds_table(QtWidgets.QWidget):
    def __init__(
        self, width: float, height: float, parent=None, x: Optional[float] = 0, y: Optional[float] = 0
    ):
        super().__init__(parent=parent)
        self.width = width
        self.height = height
        self.parent = parent
        self.x = x or self.width / 48
        self.y = y or self.height / 2.7

    def setup(self):
        self.pds_table_frame = QtWidgets.QFrame(self.parent)
        self.pds_table_frame.setGeometry(QtCore.QRect(self.x, self.y, self.width / 3.43, self.height / 2.16))
        self.pds_table_frame.setStyleSheet("")
        self.pds_table_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pds_table_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pds_table_frame.setObjectName("pds_table_frame")
        self.pds_table_title = QtWidgets.QLabel(self.pds_table_frame)
        self.pds_table_title.setGeometry(
            QtCore.QRect(
                self.width / 192,
                self.height / 108,
                self.width / 3.56,
                self.height / 46.96,
            )
        )
        font = QtGui.QFont()
        font.setPointSize(self.width / 128)
        self.pds_table_title.setFont(font)
        self.pds_table_title.setAlignment(QtCore.Qt.AlignCenter)
        self.pds_table_title.setObjectName("pds_table_title")
        self.layoutWidget_19 = QtWidgets.QWidget(self.pds_table_frame)
        self.layoutWidget_19.setGeometry(
            QtCore.QRect(self.width / 192, self.height / 27, self.width / 3.56, self.height / 2.4)
        )
        self.layoutWidget_19.setObjectName("layoutWidget_19")
        self.pds_table = QtWidgets.QVBoxLayout(self.layoutWidget_19)
        self.pds_table.setContentsMargins(11, 11, 11, 11)
        self.pds_table.setSpacing(0)
        self.pds_table.setObjectName("pds_table")
        self.pds_table_head = QtWidgets.QHBoxLayout()
        self.pds_table_head.setSpacing(0)
        self.pds_table_head.setObjectName("pds_table_head")
        self.flag_title = QtWidgets.QLabel(self.layoutWidget_19)
        self.flag_title.setAlignment(QtCore.Qt.AlignCenter)
        self.flag_title.setObjectName("flag_title")
        self.pds_table_head.addWidget(self.flag_title)
        self.line_406 = QtWidgets.QFrame(self.layoutWidget_19)
        self.line_406.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_406.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_406.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_406.setObjectName("line_406")
        self.pds_table_head.addWidget(self.line_406)
        self.state_title = QtWidgets.QLabel(self.layoutWidget_19)
        self.state_title.setAlignment(QtCore.Qt.AlignCenter)
        self.state_title.setObjectName("state_title")
        self.pds_table_head.addWidget(self.state_title)
        self.line_407 = QtWidgets.QFrame(self.layoutWidget_19)
        self.line_407.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_407.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_407.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_407.setObjectName("line_407")
        self.pds_table_head.addWidget(self.line_407)
        self.fan_title = QtWidgets.QLabel(self.layoutWidget_19)
        self.fan_title.setAlignment(QtCore.Qt.AlignCenter)
        self.fan_title.setObjectName("fan_title")
        self.pds_table_head.addWidget(self.fan_title)
        self.line_408 = QtWidgets.QFrame(self.layoutWidget_19)
        self.line_408.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_408.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_408.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_408.setObjectName("line_408")
        self.pds_table_head.addWidget(self.line_408)
        self.speed_title_15 = QtWidgets.QLabel(self.layoutWidget_19)
        self.speed_title_15.setAlignment(QtCore.Qt.AlignCenter)
        self.speed_title_15.setObjectName("speed_title_15")
        self.pds_table_head.addWidget(self.speed_title_15)
        self.pds_table.addLayout(self.pds_table_head)
        self.line_409 = QtWidgets.QFrame(self.layoutWidget_19)
        self.line_409.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_409.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_409.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_409.setObjectName("line_409")
        self.pds_table.addWidget(self.line_409)
        self.first_row = QtWidgets.QHBoxLayout()
        self.first_row.setSpacing(0)
        self.first_row.setObjectName("first_row")
        self.overvoltage_label = QtWidgets.QLabel(self.layoutWidget_19)
        self.overvoltage_label.setAlignment(QtCore.Qt.AlignCenter)
        self.overvoltage_label.setObjectName("overvoltage_label")
        self.first_row.addWidget(self.overvoltage_label)
        self.line_410 = QtWidgets.QFrame(self.layoutWidget_19)
        self.line_410.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_410.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_410.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_410.setObjectName("line_410")
        self.first_row.addWidget(self.line_410)
        self.overvoltage_state = QtWidgets.QLabel(self.layoutWidget_19)
        self.overvoltage_state.setAlignment(QtCore.Qt.AlignCenter)
        self.overvoltage_state.setObjectName("overvoltage_state")
        self.first_row.addWidget(self.overvoltage_state)
        self.line_411 = QtWidgets.QFrame(self.layoutWidget_19)
        self.line_411.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_411.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_411.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_411.setObjectName("line_411")
        self.first_row.addWidget(self.line_411)
        self.bigfan_label = QtWidgets.QLabel(self.layoutWidget_19)
        self.bigfan_label.setAlignment(QtCore.Qt.AlignCenter)
        self.bigfan_label.setObjectName("bigfan_label")
        self.first_row.addWidget(self.bigfan_label)
        self.line_412 = QtWidgets.QFrame(self.layoutWidget_19)
        self.line_412.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_412.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_412.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_412.setObjectName("line_412")
        self.first_row.addWidget(self.line_412)
        self.bigfan_speed = QtWidgets.QLabel(self.layoutWidget_19)
        self.bigfan_speed.setAlignment(QtCore.Qt.AlignCenter)
        self.bigfan_speed.setObjectName("bigfan_speed")
        self.first_row.addWidget(self.bigfan_speed)
        self.pds_table.addLayout(self.first_row)
        self.line_413 = QtWidgets.QFrame(self.layoutWidget_19)
        self.line_413.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_413.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_413.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_413.setObjectName("line_413")
        self.pds_table.addWidget(self.line_413)
        self.second_row = QtWidgets.QHBoxLayout()
        self.second_row.setSpacing(0)
        self.second_row.setObjectName("second_row")
        self.undervoltage_label = QtWidgets.QLabel(self.layoutWidget_19)
        self.undervoltage_label.setAlignment(QtCore.Qt.AlignCenter)
        self.undervoltage_label.setObjectName("undervoltage_label")
        self.second_row.addWidget(self.undervoltage_label)
        self.line_414 = QtWidgets.QFrame(self.layoutWidget_19)
        self.line_414.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_414.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_414.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_414.setObjectName("line_414")
        self.second_row.addWidget(self.line_414)
        self.undervoltage_state = QtWidgets.QLabel(self.layoutWidget_19)
        self.undervoltage_state.setAlignment(QtCore.Qt.AlignCenter)
        self.undervoltage_state.setObjectName("undervoltage_state")
        self.second_row.addWidget(self.undervoltage_state)
        self.line_415 = QtWidgets.QFrame(self.layoutWidget_19)
        self.line_415.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_415.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_415.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_415.setObjectName("line_415")
        self.second_row.addWidget(self.line_415)
        self.littlefan_label = QtWidgets.QLabel(self.layoutWidget_19)
        self.littlefan_label.setAlignment(QtCore.Qt.AlignCenter)
        self.littlefan_label.setObjectName("littlefan_label")
        self.second_row.addWidget(self.littlefan_label)
        self.line_416 = QtWidgets.QFrame(self.layoutWidget_19)
        self.line_416.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_416.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_416.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_416.setObjectName("line_416")
        self.second_row.addWidget(self.line_416)
        self.littlefan_speed = QtWidgets.QLabel(self.layoutWidget_19)
        self.littlefan_speed.setAlignment(QtCore.Qt.AlignCenter)
        self.littlefan_speed.setObjectName("littlefan_speed")
        self.second_row.addWidget(self.littlefan_speed)
        self.pds_table.addLayout(self.second_row)
        self.line_417 = QtWidgets.QFrame(self.layoutWidget_19)
        self.line_417.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_417.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_417.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_417.setObjectName("line_417")
        self.pds_table.addWidget(self.line_417)
        self.third_row = QtWidgets.QHBoxLayout()
        self.third_row.setSpacing(0)
        self.third_row.setObjectName("third_row")
        self.critical_error_label = QtWidgets.QLabel(self.layoutWidget_19)
        self.critical_error_label.setAlignment(QtCore.Qt.AlignCenter)
        self.critical_error_label.setObjectName("critical_error_label")
        self.third_row.addWidget(self.critical_error_label)
        self.line_418 = QtWidgets.QFrame(self.layoutWidget_19)
        self.line_418.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_418.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_418.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_418.setObjectName("line_418")
        self.third_row.addWidget(self.line_418)
        self.critical_error_state = QtWidgets.QLabel(self.layoutWidget_19)
        self.critical_error_state.setAlignment(QtCore.Qt.AlignCenter)
        self.critical_error_state.setObjectName("critical_error_state")
        self.third_row.addWidget(self.critical_error_state)
        self.pds_table.addLayout(self.third_row)

        _translate = QtCore.QCoreApplication.translate

        self.pds_table_title.setText(_translate("MainWindow", "PDS Table"))
        self.flag_title.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center">Flag</p><p align="center">(Error)</p></body></html>',
            )
        )
        self.state_title.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center">State</p><p align="center">(On / Off)</p></body></html>',
            )
        )
        self.fan_title.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center">Fan</p><p align="center">(Number)</p></body></html>',
            )
        )
        self.speed_title_15.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center">Speed</p><p align="center">(%)</p></body></html>',
            )
        )
        self.overvoltage_label.setText(_translate("MainWindow", "Overvoltage"))
        self.overvoltage_state.setText(_translate("MainWindow", "-"))
        self.bigfan_label.setText(_translate("MainWindow", "Big Fan"))
        self.bigfan_speed.setText(_translate("MainWindow", "-"))
        self.undervoltage_label.setText(_translate("MainWindow", "Undervoltage"))
        self.undervoltage_state.setText(_translate("MainWindow", "-"))
        self.littlefan_label.setText(_translate("MainWindow", "Little Fan"))
        self.littlefan_speed.setText(_translate("MainWindow", "-"))
        self.critical_error_label.setText(_translate("MainWindow", "Critical Error"))
        self.critical_error_state.setText(_translate("MainWindow", "-"))
