# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/controller/resource/PluginUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from utils.helpers import Stream
from PyQt5 import QtWidgets, QtCore


class Autonomy_Ui(QtWidgets.QWidget):
    def __init__(self, width: float, height: float, publisher, parent=None):
        super().__init__()
        self.width = width
        self.height = height
        self.parent = parent
        self.topic = "/video0/ARViz"

        self.setObjectName("autonomy")
        self.setupUi()

    def setupUi(self):
        self.stream_screen = Stream(0, self.width, self.height, self.parent, topic=self.topic)
        self.stream_screen.setup()

        self.layout_container = QtWidgets.QWidget(self.parent)
        self.layout_container.setGeometry(0, 0, 200, 200)
        self.button_layout = QtWidgets.QVBoxLayout(self.layout_container)

        self.start_mapping_button = QtWidgets.QPushButton()
        self.start_mapping_button.setText("Start Mapping")
        self.button_layout.addWidget(self.start_mapping_button)

        self.save_map_button = QtWidgets.QPushButton()
        self.save_map_button.setText("Save Map")
        self.button_layout.addWidget(self.save_map_button)

        self.start_nav_button = QtWidgets.QPushButton()
        self.start_nav_button.setText("Start Nav")
        self.button_layout.addWidget(self.start_nav_button)

        self.follow_planned_path_button = QtWidgets.QPushButton()
        self.follow_planned_path_button.setText("Follow Planned Path")
        self.button_layout.addWidget(self.follow_planned_path_button)

        self.stop_button = QtWidgets.QPushButton()
        self.stop_button.setText("STOP (Space)")
        self.stop_button.setStyleSheet("background-color: red")
        self.button_layout.addWidget(self.stop_button)

        # self.rviz_container = QtWidgets.QWidget(self.parent)
        # self.rviz_layout = QtWidgets.QVBoxLayout(self.rviz_container)
        # self.rviz_widget = rviz.VisualizationFrame()
        # self.rviz_widget.setFixedFrame("/map")
        # self.rviz_layout.addWidget(self.rviz_widget)
