# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'science.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from utils.helpers import Stream
from utils.logger import Log_browser


class Science_Ui(QtWidgets.QWidget):
    def __init__(self, width: float, height: float, publisher, parent=None, MainWindow=None):
        super().__init__()
        self.width = width
        self.height = height
        self.parent = parent
        self.publisher = publisher
        self.topic = ["Carousel", "cv_camera/image_raw"]

        self.setObjectName("science")
        self.setupUi()

    def setupUi(self):
        self.stream_screen = Stream(
            0,
            self.width,
            self.height,
            self.parent,
            self.width / 48,
            self.height / 2.6,
            topic=self.topic,
        )
        self.stream_screen.setup()

        self.log_browser = Log_browser(self.width, self.height, self.publisher, self.parent)
        self.log_browser.setup()

        self.list_commands_button = QtWidgets.QPushButton(self.parent)
        self.list_commands_button.setGeometry(
            QtCore.QRect(self.width * 0.594, self.height * 0.75, self.width * 0.068, self.height * 0.075)
        )
        self.list_commands_button.setObjectName("list_commands_button")
        self.stop_button = QtWidgets.QPushButton(self.parent)
        self.stop_button.setGeometry(
            QtCore.QRect(self.width * 0.71, self.height * 0.75, self.width * 0.068, self.height * 0.075)
        )
        self.stop_button.setObjectName("stop_button")
        self.stop_button.setStyleSheet("background-color: red")
        self.spin_mix_button = QtWidgets.QPushButton(self.parent)
        self.spin_mix_button.setGeometry(
            QtCore.QRect(self.width * 0.82, self.height * 0.75, self.width * 0.068, self.height * 0.075)
        )
        self.spin_mix_button.setObjectName("spin_mix_button")
        self.science_table_frame = QtWidgets.QFrame(self.parent)
        self.science_table_frame.setGeometry(
            QtCore.QRect(self.width * 0.578, self.height * 0.046, self.width * 0.33, self.height * 0.64)
        )
        self.science_table_frame.setStyleSheet("")
        self.science_table_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.science_table_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.science_table_frame.setObjectName("science_table_frame")
        self.science_table_title = QtWidgets.QLabel(self.science_table_frame)
        self.science_table_title.setGeometry(
            QtCore.QRect(self.width / 192, self.height / 108, self.width * 0.318, self.height * 0.021)
        )
        font = QtGui.QFont()
        font.setPointSize(self.width / 128)
        self.science_table_title.setFont(font)
        self.science_table_title.setAlignment(QtCore.Qt.AlignCenter)
        self.science_table_title.setObjectName("science_table_title")
        self.widget = QtWidgets.QWidget(self.science_table_frame)
        self.widget.setGeometry(
            QtCore.QRect(self.width / 96, self.height / 7.71, self.width * 0.3, self.height / 2.298)
        )
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(
            self.width / 174.54, self.height / 98.18, self.width / 174.54, self.height / 98.18
        )
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.vial1 = QtWidgets.QRadioButton(self.widget)
        self.vial1.setStyleSheet("align: center")
        self.vial1.setObjectName("vial1")
        self.verticalLayout_2.addWidget(self.vial1)
        self.vial2 = QtWidgets.QRadioButton(self.widget)
        self.vial2.setObjectName("vial2")
        self.verticalLayout_2.addWidget(self.vial2)
        self.vial3 = QtWidgets.QRadioButton(self.widget)
        self.vial3.setObjectName("vial3")
        self.verticalLayout_2.addWidget(self.vial3)
        self.vial4 = QtWidgets.QRadioButton(self.widget)
        self.vial4.setObjectName("vial4")
        self.verticalLayout_2.addWidget(self.vial4)
        self.vial5 = QtWidgets.QRadioButton(self.widget)
        self.vial5.setObjectName("vial5")
        self.verticalLayout_2.addWidget(self.vial5)
        self.vial6 = QtWidgets.QRadioButton(self.widget)
        self.vial6.setObjectName("vial6")
        self.verticalLayout_2.addWidget(self.vial6)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.vial1_status = QtWidgets.QLabel(self.widget)
        self.vial1_status.setAlignment(QtCore.Qt.AlignCenter)
        self.vial1_status.setObjectName("vial1_status")
        self.verticalLayout.addWidget(self.vial1_status)
        self.vial2_status = QtWidgets.QLabel(self.widget)
        self.vial2_status.setAlignment(QtCore.Qt.AlignCenter)
        self.vial2_status.setObjectName("vial2_status")
        self.verticalLayout.addWidget(self.vial2_status)
        self.vial3_status = QtWidgets.QLabel(self.widget)
        self.vial3_status.setAlignment(QtCore.Qt.AlignCenter)
        self.vial3_status.setObjectName("vial3_status")
        self.verticalLayout.addWidget(self.vial3_status)
        self.vial4_status = QtWidgets.QLabel(self.widget)
        self.vial4_status.setAlignment(QtCore.Qt.AlignCenter)
        self.vial4_status.setObjectName("vial4_status")
        self.verticalLayout.addWidget(self.vial4_status)
        self.vial5_status = QtWidgets.QLabel(self.widget)
        self.vial5_status.setAlignment(QtCore.Qt.AlignCenter)
        self.vial5_status.setObjectName("vial5_status")
        self.verticalLayout.addWidget(self.vial5_status)
        self.vial6_status = QtWidgets.QLabel(self.widget)
        self.vial6_status.setAlignment(QtCore.Qt.AlignCenter)
        self.vial6_status.setObjectName("vial6_status")
        self.verticalLayout.addWidget(self.vial6_status)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.line_2 = QtWidgets.QFrame(self.widget)
        self.line_2.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.vial1_ccd_result = QtWidgets.QLabel(self.widget)
        self.vial1_ccd_result.setAlignment(QtCore.Qt.AlignCenter)
        self.vial1_ccd_result.setObjectName("vial1_ccd_result")
        self.verticalLayout_3.addWidget(self.vial1_ccd_result)
        self.vial2_ccd_result = QtWidgets.QLabel(self.widget)
        self.vial2_ccd_result.setAlignment(QtCore.Qt.AlignCenter)
        self.vial2_ccd_result.setObjectName("vial2_ccd_result")
        self.verticalLayout_3.addWidget(self.vial2_ccd_result)
        self.vial3_ccd_result = QtWidgets.QLabel(self.widget)
        self.vial3_ccd_result.setAlignment(QtCore.Qt.AlignCenter)
        self.vial3_ccd_result.setObjectName("vial3_ccd_result")
        self.verticalLayout_3.addWidget(self.vial3_ccd_result)
        self.vial4_ccd_result = QtWidgets.QLabel(self.widget)
        self.vial4_ccd_result.setAlignment(QtCore.Qt.AlignCenter)
        self.vial4_ccd_result.setObjectName("vial4_ccd_result")
        self.verticalLayout_3.addWidget(self.vial4_ccd_result)
        self.vial5_ccd_result = QtWidgets.QLabel(self.widget)
        self.vial5_ccd_result.setAlignment(QtCore.Qt.AlignCenter)
        self.vial5_ccd_result.setObjectName("vial5_ccd_result")
        self.verticalLayout_3.addWidget(self.vial5_ccd_result)
        self.vial6_ccd_result = QtWidgets.QLabel(self.widget)
        self.vial6_ccd_result.setAlignment(QtCore.Qt.AlignCenter)
        self.vial6_ccd_result.setObjectName("vial6_ccd_result")
        self.verticalLayout_3.addWidget(self.vial6_ccd_result)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.line_3 = QtWidgets.QFrame(self.widget)
        self.line_3.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout.addWidget(self.line_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.vial1_ramen_result = QtWidgets.QLabel(self.widget)
        self.vial1_ramen_result.setAlignment(QtCore.Qt.AlignCenter)
        self.vial1_ramen_result.setObjectName("vial1_ramen_result")
        self.verticalLayout_4.addWidget(self.vial1_ramen_result)
        self.vial2_ramen_result = QtWidgets.QLabel(self.widget)
        self.vial2_ramen_result.setAlignment(QtCore.Qt.AlignCenter)
        self.vial2_ramen_result.setObjectName("vial2_ramen_result")
        self.verticalLayout_4.addWidget(self.vial2_ramen_result)
        self.vial3_ramen_result = QtWidgets.QLabel(self.widget)
        self.vial3_ramen_result.setAlignment(QtCore.Qt.AlignCenter)
        self.vial3_ramen_result.setObjectName("vial3_ramen_result")
        self.verticalLayout_4.addWidget(self.vial3_ramen_result)
        self.vial4_ramen_result = QtWidgets.QLabel(self.widget)
        self.vial4_ramen_result.setAlignment(QtCore.Qt.AlignCenter)
        self.vial4_ramen_result.setObjectName("vial4_ramen_result")
        self.verticalLayout_4.addWidget(self.vial4_ramen_result)
        self.vial5_ramen_result = QtWidgets.QLabel(self.widget)
        self.vial5_ramen_result.setAlignment(QtCore.Qt.AlignCenter)
        self.vial5_ramen_result.setObjectName("vial5_ramen_result")
        self.verticalLayout_4.addWidget(self.vial5_ramen_result)
        self.vial6_ramen_result = QtWidgets.QLabel(self.widget)
        self.vial6_ramen_result.setAlignment(QtCore.Qt.AlignCenter)
        self.vial6_ramen_result.setObjectName("vial6_ramen_result")
        self.verticalLayout_4.addWidget(self.vial6_ramen_result)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.widget1 = QtWidgets.QWidget(self.science_table_frame)
        self.widget1.setGeometry(
            QtCore.QRect(self.width / 96, self.height / 1.71, self.width / 3.31, self.height / 21.6)
        )
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(
            self.width / 174.54, self.height / 98.18, self.width / 174.54, self.height / 98.18
        )
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.total_used_vials = QtWidgets.QLabel(self.widget1)
        self.total_used_vials.setAlignment(QtCore.Qt.AlignCenter)
        self.total_used_vials.setObjectName("total_used_vials")
        self.horizontalLayout_2.addWidget(self.total_used_vials)
        self.line_4 = QtWidgets.QFrame(self.widget1)
        self.line_4.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_2.addWidget(self.line_4)
        self.used_vials = QtWidgets.QLabel(self.widget1)
        self.used_vials.setAlignment(QtCore.Qt.AlignCenter)
        self.used_vials.setObjectName("used_vials")
        self.horizontalLayout_2.addWidget(self.used_vials)
        self.widget2 = QtWidgets.QWidget(self.science_table_frame)
        self.widget2.setGeometry(
            QtCore.QRect(self.width / 96, self.height / 21.6, self.width / 3.31, self.height / 15.43)
        )
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_3.setContentsMargins(
            self.width / 174.54, self.height / 98.18, self.width / 174.54, self.height / 98.18
        )
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.science_status_title_2 = QtWidgets.QLabel(self.widget2)
        self.science_status_title_2.setAlignment(QtCore.Qt.AlignCenter)
        self.science_status_title_2.setObjectName("science_status_title_2")
        self.horizontalLayout_3.addWidget(self.science_status_title_2)
        self.line_6 = QtWidgets.QFrame(self.widget2)
        self.line_6.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.horizontalLayout_3.addWidget(self.line_6)
        self.science_status_title = QtWidgets.QLabel(self.widget2)
        self.science_status_title.setAlignment(QtCore.Qt.AlignCenter)
        self.science_status_title.setObjectName("science_status_title")
        self.horizontalLayout_3.addWidget(self.science_status_title)
        self.line_5 = QtWidgets.QFrame(self.widget2)
        self.line_5.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_3.addWidget(self.line_5)
        self.ccd_test_result_title = QtWidgets.QLabel(self.widget2)
        self.ccd_test_result_title.setAlignment(QtCore.Qt.AlignCenter)
        self.ccd_test_result_title.setObjectName("ccd_test_result_title")
        self.horizontalLayout_3.addWidget(self.ccd_test_result_title)
        self.line_8 = QtWidgets.QFrame(self.widget2)
        self.line_8.setStyleSheet("background-color: rgb(238, 238, 236);")
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.horizontalLayout_3.addWidget(self.line_8)
        self.ramen_test_result_title = QtWidgets.QLabel(self.widget2)
        self.ramen_test_result_title.setAlignment(QtCore.Qt.AlignCenter)
        self.ramen_test_result_title.setObjectName("ramen_test_result_title")
        self.horizontalLayout_3.addWidget(self.ramen_test_result_title)

        self.next_vial_button = QtWidgets.QPushButton(self.parent)
        self.previous_vial_button = QtWidgets.QPushButton(self.parent)

        self.next_vial_button.setObjectName("next_vial_button")
        self.previous_vial_button.setObjectName("previous_vial_button")

        self.next_vial_button.setText("Next Vial")
        self.previous_vial_button.setText("Previous Vial")
        self.next_vial_button.setGeometry(
            self.width / 1.35, self.height / 1.45, self.width / 19.2, self.height / 21.6
        )
        self.previous_vial_button.setGeometry(
            self.width / 1.455, self.height / 1.45, self.width / 19.2, self.height / 21.6
        )

        self.servo_angle_input = QtWidgets.QDoubleSpinBox(self.parent)
        self.servo_angle_input.setGeometry(
            QtCore.QRect(self.width / 2.13, self.height / 4.696, self.width / 27.43, self.height / 43.2)
        )
        self.servo_angle_input.setDecimals(1)
        self.servo_angle_input.setMaximum(360.0)
        self.servo_angle_input.setSingleStep(10.0)
        self.servo_angle_input.setObjectName("servo_angle_input")
        self.servo_angle_label = QtWidgets.QLabel(self.parent)
        self.servo_angle_label.setGeometry(
            QtCore.QRect(self.width / 2.06, self.height / 5.4, self.width / 21.33, self.height / 63.53)
        )
        self.servo_angle_label.setObjectName("label")
        self.set_servo_angle_button = QtWidgets.QPushButton(self.parent)
        self.set_servo_angle_button.setGeometry(
            QtCore.QRect(self.width / 1.959, self.height / 4.696, self.width / 32, self.height / 43.2)
        )
        self.set_servo_angle_button.setObjectName("pushButton")

        self.get_status_button = QtWidgets.QPushButton(self.parent)
        self.get_status_button.setText("Get Status")
        self.get_status_button.setObjectName("get_status_button")
        self.get_status_button.setGeometry(
            QtCore.QRect(self.width / 2.13, self.height / 3, self.width * 0.068, self.height * 0.075)
        )

        self.retranslateUi()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.list_commands_button.setText(_translate("MainWindow", "List Commands\n" "(L)"))
        self.stop_button.setText(_translate("MainWindow", "STOP (Space)"))
        self.spin_mix_button.setText(_translate("MainWindow", "Spin Mix (S)"))
        self.science_table_title.setText(_translate("MainWindow", "Science Table"))
        self.vial1.setText(_translate("MainWindow", "#1"))
        self.vial2.setText(_translate("MainWindow", "#2"))
        self.vial3.setText(_translate("MainWindow", "#3"))
        self.vial4.setText(_translate("MainWindow", "#4"))
        self.vial5.setText(_translate("MainWindow", "#5"))
        self.vial6.setText(_translate("MainWindow", "#6"))
        self.vial1_status.setText(_translate("MainWindow", "Unused"))
        self.vial2_status.setText(_translate("MainWindow", "Unused"))
        self.vial3_status.setText(_translate("MainWindow", "Unused"))
        self.vial4_status.setText(_translate("MainWindow", "Unused"))
        self.vial5_status.setText(_translate("MainWindow", "Unused"))
        self.vial6_status.setText(_translate("MainWindow", "Unused"))
        self.vial1_ccd_result.setText(_translate("MainWindow", "-"))
        self.vial2_ccd_result.setText(_translate("MainWindow", "-"))
        self.vial3_ccd_result.setText(_translate("MainWindow", "-"))
        self.vial4_ccd_result.setText(_translate("MainWindow", "-"))
        self.vial5_ccd_result.setText(_translate("MainWindow", "-"))
        self.vial6_ccd_result.setText(_translate("MainWindow", "-"))
        self.vial1_ramen_result.setText(_translate("MainWindow", "-"))
        self.vial2_ramen_result.setText(_translate("MainWindow", "-"))
        self.vial3_ramen_result.setText(_translate("MainWindow", "-"))
        self.vial4_ramen_result.setText(_translate("MainWindow", "-"))
        self.vial5_ramen_result.setText(_translate("MainWindow", "-"))
        self.vial6_ramen_result.setText(_translate("MainWindow", "-"))
        self.total_used_vials.setText(_translate("MainWindow", "Total Vials Used"))
        self.used_vials.setText(_translate("MainWindow", "0"))

        self.servo_angle_label.setText(_translate("MainWindow", "Servo Angle"))
        self.set_servo_angle_button.setText(_translate("MainWindow", "Set"))

        self.science_status_title_2.setText(
            _translate("MainWindow", '<html><head/><body><p align="center">Vial Selection</p></body></html>')
        )
        self.science_status_title.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center">Status</p><p align="center">(Used / Unused)</p></body></html>',
            )
        )
        self.ccd_test_result_title.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center">Test Result</p><p align="center">CCD</p></body></html>',
            )
        )
        self.ramen_test_result_title.setText(
            _translate(
                "MainWindow",
                '<html><head/><body><p align="center">Test Result</p><p align="center">Ramen Spec</p></body></html>',
            )
        )
